### ISSUE TITLE
Additional Info snippet is showing wrong data

### ISSUE THREAD

**Issue by pdelboca** [datopian/ckanext-versioning#21]
Two distinct issues

* [x] Contributors and Licenses ending up in extras: **FIXED see https://github.com/frictionlessdata/frictionless-ckan-mapper/issues/42**
* Tag handling: See #32 now

## Background

When accesing the `show` page for datasets, the addition info section is showing extra metadata. This may be related on how are we handling package `extras` field.

![image](https://user-images.githubusercontent.com/6672339/87325947-7e718300-c508-11ea-83a0-f216c345b739.png)

### Tips to Reproduce

- Create a dataset
- Add a Maintainer
- Create a version
- Click to see the version
- The **Additional Info** table is not showing the information properly

Also, when promoting a dataset a `tracking_summary` is append to the Additional Field info:
![image](https://user-images.githubusercontent.com/6672339/87326596-53d3fa00-c509-11ea-81d1-ee62950bd401.png)

**Comment by pdelboca** [comment]
This error is related to the Frictionless <-> CKAN mapper. more info related tags: 
```
When doing a round tripping, if I add a **tag** to the package in CKAN the result of `package_show` is the following one:

```
 'tags': [{'display_name': u'FancyTag',
           'id': u'b273a236-e4f8-498b-a64c-fc8f10384afd',
           'name': u'FancyTag',
           'state': u'active',
           'vocabulary_id': None},
          {'display_name': u'NewFancyTag',
           'id': u'8d9e96e0-cf58-44e1-90eb-1b34f778f442',
           'name': u'NewFancyTag',
           'state': u'active',
           'vocabulary_id': None}],
```

However, the library is only mapping the name of the tag:
```
 'keywords': [u'FancyTag', u'NewFancyTag'],
```

So if I do a reconversion using `ftc.package()` it will return:
```
'tags': [{'name': u'FancyTag'}, {'name': u'NewFancyTag'}],
```

Which is missing `id`, `display_name`, `state` and `vocabulary_id`.
```

I have also added a comment it the original ticket: https://github.com/frictionlessdata/frictionless-ckan-mapper/issues/33

**Comment by rufuspollock** [comment]
@pdelboca the question here is 2 fold as i understand it:

* What should we do with tags in ckan <=> frictionless Should we just store name/id and and have ckanext-versioning look up tag info ... or should we store everything into metastore and then convert back
* Regarding extras that come from CKAN i.e. contributors and licenses: i think we may want to think a bit more carefully here about the default case.

**Comment by rufuspollock** [comment]
FIXED. Contributors and licenses done and tags is in discussion in #32
