### ISSUE TITLE
Implement Purge action to delete repositories

### ISSUE THREAD

**Issue by pdelboca** [datopian/ckanext-versioning#36]
CKAN has an action called `dataset_purge` that we can be leverage to implement the deletion of repositories. The behaviour should be:
 - When deleting a dataset, do nothing with the repo (We theoretically could put it into archive status but then we cannot undo that action through the API)
 - When purging the dataset, delete the repo.

### Note:
 - Even when this action exist, the current `trash` action of the admin controller does not use it. This action is only used by the `purge` cli command.
 - We may need to write our own `trash` view to use this action.

**Comment by shevron** [comment]
@pdelboca what is the behavior expected by users? If currently this is only exposed in CLI, shouldn't we keep it that way?
