### ISSUE TITLE
Using FilesystemStorage for tests

### ISSUE THREAD

**Issue by pdelboca** [datopian/ckanext-versioning#6]
Per discussion in #1:

@shevron 

> I would make this _get_metastore_backend and not assume we are using GitHub. The whole point of metastore-lib is to abstract that away. Just use metastore.create_metastore and pass it two config options: backend_type and backend_config. The latter can be a dict - I know CKAN allows that. This allows us to use the GitHub storage in production and the Filesystem storage locally / in testing, and also any other backend in the future without changing the implementation.

@pdelboca 

> I did this but cannot use backend_config={"uri":"mem://"} for tests. I guess that since I'm creating backend objects each time I need it it does not maintain the data between tests. Any idea on how to fix it? I can use backend_config={"uri":"/my/path/folder"} but i need to clean it manually after each test. Even as the same test calls create/show, and I'm creating two backend objects it will fail.

@shevron 

> Hmm... good question. We can surely use a disk-based storage as you did, and then just delete that directory on test teardown. I didn't try but it should work. It does bring up a question of whether or not we want the backend object somehow persisted in memory e.g. on the Plugin object or even in the module level. Maybe if CKAN has something like request-locals we can add another function to ckanext/versioning/common.py that calls get_metastore_backend and caches the backend object as a request-local variable. That will allow us to have a single backend object as long as we are on the same request context, which makes sense. I'm not sure it's worth it though, and will not play nice with tests that do not run inside a request context.

**Comment by shevron** [comment]
This will be fixed by #11
